=== pssslearning/jsonschematestsnv/schema/json/corpserv/corpserv-cdc-signaturit-document-flow-events-v1.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://pssslearning.github.io/jsonschematestsnv/schema/json/corpserv/corpserv-cdc-signaturit-document-flow-events-v1.json",
  "type": "object",
  "title": "corpserv-cdc-signaturit-document-flow-events-v1 (Domain:CorpServ)(Classification: CDC)(Version: v1.0.0)",
  "description": "Mensaje recibido por subscripcion de eventos de Signaturit",
  "required": [
    "metadata",
    "document",
    "created_at",
    "type"
  ],
  "properties": {
    "metadata": {
      "$ref": "https://pssslearning.github.io/jsonschematestsnv/schema/json/shared/shared-sys-kafka-message-metadata-v1.json#"
    },
    "document": {
      "$id": "#/properties/document",
      "type": "object",
      "title": "Datos asociados al Documento objeto de Firma",
      "description": "Datos asociados al Documento objeto de Firma incluyendo los diferentes eventos asociados al curso de su tratamiento.",
      "required": [
        "created_at",
        "file",
        "id",
        "events",
        "signature",
        "email",
        "name",
        "status"
      ],
      "properties": {
        "created_at": {
          "$id": "#/properties/document/properties/created_at",
          "type": "string",
          "title": "Fecha de Creación del Documento",
          "description": "Fecha en la que se incia el flujo de proceso de firma del documento.",
          "examples": [
            "2021-01-20T12:46:43+0000"
          ]
        },
        "file": {
          "$id": "#/properties/document/properties/file",
          "type": "object",
          "title": "Información del archivo objeto de firma",
          "description": "Información del archivo objeto de firma",
            "required": [
            "name",
            "pages",
            "size"
          ],
          "properties": {
            "name": {
              "$id": "#/properties/document/properties/file/properties/name",
              "type": "string",
              "title": "Nombre del archivo",
              "description": "Nombre del Archivo",
              "examples": [
                "LoremIpsum1.pdf"
              ]
            },
            "pages": {
              "$id": "#/properties/document/properties/file/properties/pages",
              "type": "integer",
              "title": "Número de Páginas que contiene el documento.",
              "description": "Número de Páginas que contiene el documento.",
              "examples": [
                1
              ]
            },
            "size": {
              "$id": "#/properties/document/properties/file/properties/size",
              "type": "integer",
              "title": "Tamaño en Bytes del archivo.",
              "description": "Tamaño en Bytes del archivo.",
              "examples": [
                57844
              ]
            }
          },
          "additionalProperties": false
        },
        "id": {
          "$id": "#/properties/document/properties/id",
          "type": "string",
          "title": "Identificador único del documento.",
          "description": "Identificador único del documento objeto del flujo de tratamiento de firma.",
          "examples": [
            "7e867358-3874-4321-9459-5e8aafdf6eb9"
          ]
        },
        "events": {
          "$id": "#/properties/document/properties/events",
          "type": "array",
          "title": "Array de Eventos anteriores que ya se han producido.",
          "description": "Array de Eventos anteriores que ya se han producido durante el flujo de tratamiento de firma.",
          "additionalItems": false,
          "items": {
            "$id": "#/properties/document/properties/events/items",
            "type": "object",
            "title": "Cada uno de los eventos.",
            "description": "Cada uno de los eventos que forman parte del Array.",
            "required": [
              "created_at",
              "type"
            ],
            "properties": {
              "created_at": {
                "$id": "#/properties/document/properties/events/items/properties/created_at",
                "type": "string",
                "title": "Fecha y Hora de creación del evento.",
                "description": "Fecha y Hora de creación del evento.",
                "examples": [
                  "2021-01-20T12:46:46+0000"
                ]
              },
              "type": {
                "$id": "#/properties/document/properties/events/items/properties/type",
                "type": "string",
                "title": "El Tipo de Evento que se reporta",
                "description": "An explanation about the purpose of this instance.",
                "examples": [
                  "email_processed"
                ]
              }
            },
            "additionalProperties": false
          }
        },
        "data": {
          "$id": "#/properties/document/properties/data",
          "type": "object",
          "title": "Estructura compuesta de tuplas clave-valor de los parámetros del area de formulario.",
          "description": "Estructura compuesta de tuplas clave-valor de los parámetros de los datos del documento susceptibles de ser introducidos por el destinatario.",
          "examples": [
            {
              "text_1": "12345678A",
              "text_2": "Iván J Fontalvo Olivares"
            }
          ],
         "additionalProperties": true
        },
        "signature": {
          "$id": "#/properties/document/properties/signature",
          "type": "object",
          "title": "Estructura con la información asociada a la firma.",
          "description": "Estructura con la información asociada a la firma.",
          "required": [
            "id"
          ],
          "properties": {
            "id": {
              "$id": "#/properties/document/properties/signature/properties/id",
              "type": "string",
              "title": "Identificador único asignado por Signaturit al proceso de firma asociado.",
              "description": "Identificador único asignado por Signaturit al proceso de firma asociado.",
              "examples": [
                "63fcfb72-af54-4d3c-8540-08c8a9b851b3"
              ]
            }
          },
          "additionalProperties": false
        },
        "email": {
          "$id": "#/properties/document/properties/email",
          "type": "string",
          "title": "Dirección de email del destinatario (Firmante).",
          "description": "Dirección de email del destinatario (Firmante).",
          "examples": [
            "ivan.fontalvo@cttexpress.com"
          ]
        },
        "name": {
          "$id": "#/properties/document/properties/name",
          "type": "string",
          "title": "Nombre del destinatario (Firmante).",
          "description": "Nombre del destinatario (Firmante).",
          "examples": [
            "Ivan Fontalvo Olivares"
          ]
        },
        "status": {
          "$id": "#/properties/document/properties/status",
          "type": "string",
          "title": "Estado del documento en el flujo de tratamiento de firma.",
          "description": "Estado del documento en el flujo de tratamiento de firma.",
          "examples": [
            "completed"
          ]
        }
      },
      "additionalProperties": false
    },
    "created_at": {
      "$id": "#/properties/created_at",
      "type": "string",
      "title": "Fecha y Hora de la creación del evento actual.",
      "description": "Fecha y Hora de la creación del evento actual.",
      "examples": [
        "2021-01-20T12:58:45+0000"
      ]
    },
    "type": {
      "$id": "#/properties/type",
      "type": "string",
      "title": "Tipo del evento actual.",
      "description": "Tipo del evento actual.",
      "examples": [
        "audit_trail_completed"
      ]
    }
  },
  "additionalProperties": false
}

=== pssslearning/jsonschematestsnv/samples/json/corpserv/corpserv-cdc-digital-signature-document-flow-events-v1.json
{
  "metadata": {
    "interchange_id": "6245F015-9A24-459E-B457-5B7BA33B57B3",
    "time_stamp": "2021-01-20T12:58:03.5957639+01:00",
    "correlation_id": "6245F015-9A24-459E-B457-5B7BA33B57B3",
    "source": "urn:com:cttexpress:interchange:source:signaturit",
    "data_type": "schema/json/corpserv/corpserv-cdc-digital-signature-document-flow-events-v1.json"
  },
  "document": {
    "created_at": "2021-01-20T12:46:43+0000",
    "file": {
      "name": "LoremIpsum1.pdf",
      "pages": 1,
      "size": 57844
    },
    "id": "7e867358-3874-4321-9459-5e8aafdf6eb9",
    "events": [
      {
        "created_at": "2021-01-20T12:46:46+0000",
        "type": "email_processed"
      },
      {
        "created_at": "2021-01-20T12:46:49+0000",
        "type": "email_delivered"
      },
      {
        "created_at": "2021-01-20T12:57:26+0000",
        "type": "document_opened"
      },
      {
        "created_at": "2021-01-20T12:58:37+0000",
        "type": "terms_and_conditions_accepted"
      },
      {
        "created_at": "2021-01-20T12:58:37+0000",
        "type": "document_signed"
      },
      {
        "created_at": "2021-01-20T12:58:41+0000",
        "type": "document_completed"
      }
    ],
    "data": {
      "text_1": "12345678A",
      "text_2": "Iv√°n J Fontalvo Olivares"
    },
    "signature": {
      "id": "63fcfb72-af54-4d3c-8540-08c8a9b851b3"
    },
    "email": "ivan.fontalvo@cttexpress.com",
    "name": "Ivan Fontalvo Olivares",
    "status": "completed"
  },
  "created_at": "2021-01-20T12:58:45+0000",
  "type": "audit_trail_completed"
}
